# Copyright 2026 FastLabs Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[workspace]
members = ["benchmarks", "examples", "rache", "tests-integration", "xtask"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
rust-version = "1.85"

[workspace.dependencies]
# Workspace dependencies
rache = { path = "rache" }

# Crates.io dependencies
cityhash-rs = { version = "1.0.1" }
cityhasher = { version = "0.1.0" }
clap = { version = "4.6.6", features = ["derive"] }
divan = { version = "0.1.21" }
fnv = { version = "1.0.7" }
murmur3 = { version = "0.5.2" }
twox-hash = { version = "2.1.4", default-features = false, features = [
  "std",
  "xxhash3_128",
  "xxhash3_64",
  "xxhash32",
  "xxhash64",
] }
which = { version = "8.0.6" }
xxhash-rust = { version = "0.8.18", features = ["xxh3", "xxh32", "xxh64"] }

[workspace.lints.rust]
unknown_lints = "deny"
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[workspace.metadata.release]
pre-release-commit-message = "chore: release v{{version}}"
shared-version = true
sign-tag = true
tag-name = "v{{version}}"

[profile.release]
codegen-units = 1
lto = "thin"
