# Copyright 2026 FastLabs Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
categories = ["algorithms", "no-std"]
description = "Fast, portable non-cryptographic hashes for Rust"
documentation = "https://docs.rs/hashcrew"
homepage = "https://github.com/fast/rache"
keywords = ["hash", "xxhash", "cityhash", "murmurhash", "fnv"]
name = "hashcrew"
repository = "https://github.com/fast/rache"
version = "0.1.0"

edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["std"]
std = []

[lints]
workspace = true
