[package]
name = "rache"
version = "0.1.0"
description = "Fast, portable non-cryptographic hashes for Rust"
documentation = "https://docs.rs/rache"
homepage = "https://github.com/leiysky/rache"
repository = "https://github.com/leiysky/rache"
keywords = ["hash", "xxhash", "cityhash", "murmurhash", "fnv"]
categories = ["algorithms", "no-std"]

edition.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true

[features]
default = ["std"]
std = []

[lints]
workspace = true
