[package]
name = "benchmarks"
version = "0.0.0"
publish = false

edition.workspace = true
rust-version.workspace = true

[dev-dependencies]
cityhash-rs.workspace = true
cityhasher.workspace = true
divan.workspace = true
fnv.workspace = true
murmur3.workspace = true
rache.workspace = true
twox-hash.workspace = true
xxhash-rust.workspace = true

[[bench]]
harness = false
name = "throughput"
path = "benches/throughput.rs"

[[bench]]
harness = false
name = "streaming"
path = "benches/streaming.rs"

[lints]
workspace = true
